package com.gimlism.translucent.trie.demo;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class StandardTrieWebVizDemoTest {

    /**
     * The title assertions below catch a mislabelled page; the EVENT assertions catch the defect a
     * golden provably cannot see. A StandardTrie demo that still constructed a RadixTrie would ship a
     * page titled "StandardTrie" holding a radix replay, and regenerating would make the committed
     * bytes agree with the generated bytes either way. SplitEdge/MergeEdge absence is the property
     * that actually separates the two implementations.
     */
    @Test
    void buildHtmlIsSelfContainedAndReplaysAStandardTrieNotARadixOne() {
        String html = StandardTrieWebVizDemo.buildHtml();

        // self-contained baked document, no unsubstituted tokens
        assertTrue(html.contains("<!doctype html>"), "expected a full document");
        assertTrue(html.contains("</html>"), "expected closing html tag");
        assertTrue(html.contains("\"frames\":["), "expected an injected frames blob");
        assertFalse(html.contains("/*__"), "no template token should survive");

        // the page names the structure it depicts
        assertTrue(html.contains("<title>StandardTrie — replay</title>"), "expected the StandardTrie title");
        assertFalse(html.contains("RadixTrie"), "the standard page must not name the radix trie");

        // the story ran and emitted the standard trie's vocabulary
        assertTrue(html.contains("\"type\":\"CreateNode\""), "expected one node created per character");
        assertTrue(html.contains("\"type\":\"Descend\""), "expected a walk down the chain");
        assertTrue(html.contains("\"type\":\"Put\""), "expected inserts");
        assertTrue(html.contains("\"type\":\"Remove\""), "expected removes");
        assertTrue(html.contains("\"type\":\"Prune\""), "expected the prune cascade");

        // and NOT the radix trie's — this is the assertion that discriminates
        assertFalse(html.contains("\"type\":\"SplitEdge\""), "a standard trie never splits an edge");
        assertFalse(html.contains("\"type\":\"MergeEdge\""), "a standard trie never merges an edge");

        // every edge label is a single character — the defining shape of an uncompressed trie
        assertFalse(html.contains("\"label\":\"sh\""), "labels are one character, never a compressed run");
    }
}
